name: publish docker images

on:
  push:
    tags:
      - "v*"


permissions:
  contents: read
  packages: write


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build API image
        run: |
          docker build \
            -f api/Dockerfile \
            -t ghcr.io/${{ github.repository }}:${{ github.ref_name }} \
            -t ghcr.io/${{ github.repository }}:latest \
            .

      - name: Push API image
        run: |
          docker push ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          docker push ghcr.io/${{ github.repository }}:latest